"""Reference-measured r5 longitudinal refinement. No phase warp, score or render."""
import argparse,copy,csv,hashlib,json
from pathlib import Path
import numpy as np
from scipy.optimize import least_squares
from scipy.signal import savgol_filter
from scipy.spatial.transform import Rotation
P=argparse.ArgumentParser();P.add_argument('--baseline-dir',type=Path,default=Path('/workspace/shared/hip-feedback-r4-20261003/longitudinal'));P.add_argument('--maps-dir',type=Path,default=Path('/workspace/shared/hip-feedback-r4-20261003/render/publication'));P.add_argument('--output-dir',type=Path,default=Path(__file__).resolve().parent);args=P.parse_args();B=args.baseline_dir;O=args.output_dir;O.mkdir(parents=True,exist_ok=True)
priorpath=B/'directional_keyposes_r4.json';old=json.loads(priorpath.read_text());g=old['geometry'];pivot=np.array(g['points_camera']['support_wrist']);f=640/np.tan(g['angle_x']/2);points=np.array([g['points_camera'][n] for n in ['muzzle_tip','receiver_center','support_cuff_surface']])
def project(p):
 q=(points-pivot)@Rotation.from_euler('XYZ',p[2:5]).as_matrix().T+pivot+np.r_[p[:2],p[5]]
 return q[:,:2]/-q[:,2,None]*[f,-f]+[640,360]
def angle(q):
 v=q[...,1,:]-q[...,0,:];return np.arctan2(v[...,1],v[...,0])
meta={k:copy.deepcopy(v) for k,v in old.items() if k not in ['actions','revision','source_sha256','phase_policy','review_sources','source_is_uncommitted_r3']}
meta.update({'revision':'r5 longitudinal reference-measured trough refinement','source_sha256':'d220162819fb7267aa6b93b209afc8ce5212a0692e6a4e02c5c43602b08907e3','source_is_uncommitted_combined_r4':True,'review_sources':['https://github.com/RHS059/dot_chat/pull/1#issuecomment-5972182972'],'phase_policy':'All existing native key times, periods, reference cores and repeated endpoints retained. Spatial edits only; no editorial or native phase adjustment.','actions':{}})
changes={};mapping={};gaps={}
for kind in ['forward','backward']:
 oname='hip_walk_'+kind+'_r4';n='hip_walk_'+kind+'_r5';a=old['actions'][oname];N=a['period_frames'];p0=np.array([k['params'] for k in a['keyframes'][:-1]]);q0=np.array([project(v) for v in p0]);target=q0.copy();raw=np.array(a['raw_reference_pixels']);smooth=savgol_filter(raw,5,2,axis=0,mode='wrap');scale=a['fixed_motion_scale_native_over_reference'];ref_ranges=np.ptp(smooth,axis=0)*scale;ref_angles=np.unwrap(angle(smooth));native_angles=np.unwrap(angle(q0));ref_angle_range=float(np.ptp(ref_angles));native_angle_range=float(np.ptp(native_angles));fixed_down=ref_ranges[:,1]*.10
 gaps[n]={'raw_reference_frames_half_open':a['source_range_half_open'],'reference_sha256':a['reference_sha256'],'reference_smoothing':'Savitzky-Golay5-frame quadratic, periodic wrap; same pre-existing sampling/window convention','frozen_native_over_reference_motion_scale':scale,'native_r4_range_xy_px':np.ptp(q0,axis=0).tolist(),'reference_smoothed_raw_range_xy_px':np.ptp(smooth,axis=0).tolist(),'reference_smoothed_frozen_scale_range_xy_px':ref_ranges.tolist(),'reference_minus_native_range_xy_px':(ref_ranges-np.ptp(q0,axis=0)).tolist(),'reference_screen_barrel_angle_range_degrees':float(np.degrees(ref_angle_range)),'native_r4_screen_barrel_angle_range_degrees':float(np.degrees(native_angle_range)),'screen_barrel_angle_range_gap_degrees':float(np.degrees(ref_angle_range-native_angle_range)),'native_r4_screen_barrel_angle_extrema_offsets':[int(np.argmin(native_angles)),int(np.argmax(native_angles))],'reference_screen_barrel_angle_extrema_offsets':[int(np.argmin(ref_angles)),int(np.argmax(ref_angles))],'one_tenth_reference_vertical_excursions_native_pixels':fixed_down.tolist(),'reference_smoothed_pixels':smooth.tolist(),'reference_screen_barrel_angle_degrees':np.degrees(ref_angles).tolist(),'native_r4_screen_barrel_angle_degrees':np.degrees(native_angles).tolist(),'interpretation':'Optical landmark/silhouette measurements across different weapons and cameras, not a shared-camera or anatomical registration. In backward, native vertical ranges already exceed these scaled reference ranges; the measurable angular gap is the primary supported deficit, so avoid blanket vertical scaling.'}
 lo=q0[:,:,1].min(0);span=np.ptp(q0[:,:,1],axis=0);t=(q0[:,:,1]-lo)/span;ps=[];residuals=[]
 if kind=='forward':
  target[:,:,1]+=fixed_down*t**3
  notes=['Preserve r4 muzzle/cuff lateral paths exactly and retain 38-frame cadence and figure-8 phase','Deepen each existing low by one tenth of its smoothed frozen-scale reference Y excursion, weighted by normalized native down-position cubed; no percentage multiplier of the previous revision','Exact maximum extra drops: muzzle2.672267px, receiver5.212048px, cuff4.417134px; original tops and all native vertical extrema phases retained','Solve translation, pitch, yaw and roll compensation at unchanged zero depth for threeY and twoX constraints']
  details={'muzzle_and_cuff_lateral_gain':1.0,'reference_vertical_fraction':.10,'fixed_extra_down_pixels_by_anchor':fixed_down.tolist(),'down_weight':'normalized_native_down_position ** 3','vertical_anchors':['muzzle_tip','receiver_center','support_cuff_surface'],'preserved_high_low_phases':True,'no_phase_or_key_time_change':True}
 else:
  target[:,:,1]+=fixed_down*t*(2-t)
  angle_gain=ref_angle_range/native_angle_range;target_angles=native_angles.min()+angle_gain*(native_angles-native_angles.min())
  notes=['Preserve every r4 muzzle/cuff lateral coordinate and its timing;45-frame period unchanged','Use measured screen-barrel-angle excursion: increase6.966486deg toward observed10.601394deg via a monotonic amplitude map preserving native angle-extreme phases; this is an optical constraint, not recovered3D roll','Broaden lower shoulders with normalized_down_position*(2-normalized_down_position); fixed added drops are one tenth of reference Y excursions at muzzle0.967014px and cuff2.579515px, rather than a blanket vertical gain','Solve twoX, twoY and barrel-angle constraints with translation,pitch,yaw,roll at zero depth; receiver trajectory follows the rigid pose and is not independently constrained','Corrected review range0.45-0.48s maps to Actions28-30/reference238-240; preserve these existing trough phases and repeat unchanged next loop']
  details={'muzzle_and_cuff_lateral_gain':1.0,'reference_vertical_fraction':.10,'fixed_extra_down_pixels_by_anchor':fixed_down.tolist(),'down_weight':'normalized_native_down_position * (2 - normalized_native_down_position)','vertical_anchors':['muzzle_tip','support_cuff_surface'],'screen_barrel_angle_gain':float(angle_gain),'screen_barrel_angle_target_range_degrees':float(np.degrees(ref_angle_range)),'screen_barrel_angle_policy':'Preserve native minimum angle and min/max phases; transfer measured reference excursion amplitude only','preserved_primary_high_low_phases':True,'no_phase_or_key_time_change':True}
 for i in range(N):
  def residual(z):
   p=p0[i].copy();p[:5]=z;q=project(p)
   if kind=='forward':return [*(q[:,1]-target[i,:,1]),q[0,0]-target[i,0,0],q[2,0]-target[i,2,0]]
   return [q[0,0]-target[i,0,0],q[2,0]-target[i,2,0],q[0,1]-target[i,0,1],q[2,1]-target[i,2,1],200*(angle(q)-target_angles[i])]
  sol=least_squares(residual,p0[i,:5],bounds=([-.065,-.055,-.15,-.15,-.22],[.065,.055,.15,.15,.22]),xtol=1e-12,ftol=1e-12,gtol=1e-12);p=p0[i].copy();p[:5]=sol.x;assert max(abs(sol.fun))<1e-6,(n,i,sol.fun);ps.append(p);residuals.append(float(max(abs(sol.fun))))
 ps=np.array(ps);qs=np.array([project(p) for p in ps]);entry={k:copy.deepcopy(a[k]) for k in ['direction','reference_id','reference_sha256','source_range_half_open','endpoint_source_frame','period_frames','period_s','blender_frame_range','unique_frame_range_inclusive','loop','additive','root_control','reference_points_order','native_points_order','raw_reference_pixels','fixed_motion_scale_native_over_reference']}
 entry.update({'revision_of':oname,'revision_notes':'; '.join(notes),'revision_parameters':details,'review_reference_not_source3d':True,'prior_design_sha256':hashlib.sha256(priorpath.read_bytes()).hexdigest(),'prior_params_bounds_min':p0.min(axis=0).tolist(),'prior_params_bounds_max':p0.max(axis=0).tolist(),'params_bounds_min':ps.min(axis=0).tolist(),'params_bounds_max':ps.max(axis=0).tolist(),'ideal_rigid_screen':qs.tolist(),'keyframes':[{'frame':i+1,'source_frame':a['source_range_half_open'][0]+i,'params':p.tolist()} for i,p in enumerate(ps)]+[{'frame':N+1,'source_frame':a['source_range_half_open'][1],'params':ps[0].tolist()}]});meta['actions'][n]=entry
 changes[n]={'notes':notes,'parameters':details,'max_solver_residual':max(residuals),'r4_range_xy_px':np.ptp(q0,axis=0).tolist(),'r5_predicted_range_xy_px':np.ptp(qs,axis=0).tolist(),'r4_screen_min_offsets':np.argmin(q0,axis=0).tolist(),'r4_screen_max_offsets':np.argmax(q0,axis=0).tolist(),'r5_screen_min_offsets':np.argmin(qs,axis=0).tolist(),'r5_screen_max_offsets':np.argmax(qs,axis=0).tolist(),'r4_roll_range_degrees':np.degrees([p0[:,4].min(),p0[:,4].max()]).tolist(),'r5_roll_range_degrees':np.degrees([ps[:,4].min(),ps[:,4].max()]).tolist(),'added_camera_roll_degrees_at_cuff_low':float(np.degrees(ps[np.argmax(q0[:,2,1]),4]-p0[np.argmax(q0[:,2,1]),4])),'max_absolute_added_camera_roll_degrees':float(np.degrees(np.max(abs(ps[:,4]-p0[:,4])))),'r4_screen_barrel_angle_range_degrees':float(np.degrees(np.ptp(native_angles))),'r5_screen_barrel_angle_range_degrees':float(np.degrees(np.ptp(angle(qs)))),'max_y_trace_change_by_anchor_px':np.max(abs(qs[:,:,1]-q0[:,:,1]),axis=0).tolist(),'max_x_trace_change_by_anchor_px':np.max(abs(qs[:,:,0]-q0[:,:,0]),axis=0).tolist()}
 mapfile=args.maps_dir/(oname+'_frame_map.csv');rows=list(csv.DictReader(mapfile.open()));assert len(rows)==2*N
 for out,row in enumerate(rows):
  assert int(row['output_frame'])==out and int(row['blender_frame'])==1+out%N and int(row['reference_raw_frame'])==a['source_range_half_open'][0]+out%N
  assert abs(float(row['output_time_s'])-out/60)<1e-8
 samples=[9,29,47,67] if kind=='forward' else [27,28,29,72,73,74]
 mapping[kind]={'r4_map_sha256':hashlib.sha256(mapfile.read_bytes()).hexdigest(),'all_map_rows_verified':len(rows),'selected_rows':[{k:rows[x][k] for k in ['output_frame','output_time_s','loop','reference_raw_frame','blender_frame','source_time_s']} for x in samples]}
 print(n,json.dumps(changes[n],indent=2))
(O/'directional_keyposes_r5.json').write_text(json.dumps(meta,indent=2)+'\n');(O/'motion_changes_r5.json').write_text(json.dumps({'status':'Unscored WIP; authored edits, not visual acceptance','point_order':['muzzle_tip','receiver_center','support_cuff_surface'],'actions':changes},indent=2)+'\n');(O/'review_timestamp_verification.json').write_text(json.dumps(mapping,indent=2)+'\n');(O/'reference_gap_analysis.json').write_text(json.dumps({'status':'Approximate optical evidence used to choose bounded edits; no score or calibrated reference equivalence','point_order':['muzzle_tip','receiver_center','support_cuff_surface'],'actions':gaps},indent=2)+'\n')
