"""Read native sweeps; validate intended r5 constraints, not artistic acceptance."""
import csv,hashlib,json
from pathlib import Path
import numpy as np
B=Path(__file__).resolve().parent
rows=list(csv.DictReader((B/'validation/candidate_tracks_480fps.csv').open()));prior=list(csv.DictReader(Path('/workspace/shared/hip-feedback-r4-20261003/longitudinal/validation/candidate_tracks_480fps.csv').open()));design=json.loads((B/'directional_keyposes_r5.json').read_text());result={'schema':'rust-duty-longitudinal-r5-constraint-check/v1','status':'Authored intent checks only; no reference match score or visual acceptance','candidate_sha256':hashlib.sha256((B/'halcyon_hip_longitudinal_r5.blend').read_bytes()).hexdigest(),'sweep_hz':480,'anchor_order':['muzzle_tip','receiver_center','support_cuff_surface'],'actions':{}}
def tracks(rr):return np.array([[[float(r[n+'_'+axis]) for axis in ['x','y']] for n in result['anchor_order']] for r in rr])
def angle(q):
 v=q[:,1]-q[:,0];return np.arctan2(v[:,1],v[:,0])
for direction in ['forward','backward']:
 names={v:'hip_walk_'+direction+'_'+v for v in ['r4','r5']};arrays={v:tracks([r for r in rows if r['action']==name]) for v,name in names.items()};old,new=arrays['r4'],arrays['r5'];a=design['actions'][names['r5']];n=a['period_frames'];params=a['revision_parameters'];fixed_down=np.array(params['fixed_extra_down_pixels_by_anchor']);ymin=old[:-1:8,:,1].min(0);yrange=np.ptp(old[:-1:8,:,1],axis=0);t=(old[:,:,1]-ymin)/yrange;weight=t**3 if direction=='forward' else t*(2-t);target_y=old[:,:,1]+fixed_down*weight;anchors=[0,1,2] if direction=='forward' else [0,2];primary_x_error=abs(new[:,[0,2],0]-old[:,[0,2],0]).max(0);vertical_error=abs(new[:,anchors,1]-target_y[:,anchors]).max(0)
 assert primary_x_error.max()<.01 and vertical_error.max()<.10,(direction,primary_x_error,vertical_error)
 ideal=np.array(a['ideal_rigid_screen']);native_ideal_error=float(abs(new[:-1:8]-ideal).max());assert native_ideal_error<.002
 previous=tracks([r for r in prior if r['action']==names['r4']]);preserved_error=float(abs(old-previous).max());assert preserved_error==0,preserved_error
 phase_indices=[0,1,2] if direction=='forward' else [0,2]
 phase_sets={v:{kind:[[int(i)+1 for i in np.flatnonzero(abs(q[:-1:8,j,1]-func(q[:-1:8,j,1]))<.002)] for j in phase_indices] for kind,func in [('min',np.min),('max',np.max)]} for v,q in arrays.items()}
 assert phase_sets['r4']==phase_sets['r5'],phase_sets
 report={'samples_per_revision':len(new),'retained_r4_projection_vs_prior_r4_evidence_max_error_pixels':preserved_error,'native_vs_authored_design_max_error_pixels':native_ideal_error,'dense_primary_x_constraint_error_pixels':primary_x_error.tolist(),'dense_y_constraint_error_pixels':vertical_error.tolist(),'vertical_constraint_anchor_indices':anchors,'r4_native_ranges_xy_px':np.ptp(old[:-1:8],axis=0).tolist(),'r5_native_ranges_xy_px':np.ptp(new[:-1:8],axis=0).tolist(),'constrained_vertical_extrema_native_phase_sets_unchanged_at_0p002px_tie_tolerance':True,'vertical_extrema_action_frame_sets':phase_sets,'native_min_action_frames_r4':(np.argmin(old[:-1:8],axis=0)+1).tolist(),'native_min_action_frames_r5':(np.argmin(new[:-1:8],axis=0)+1).tolist(),'native_max_action_frames_r4':(np.argmax(old[:-1:8],axis=0)+1).tolist(),'native_max_action_frames_r5':(np.argmax(new[:-1:8],axis=0)+1).tolist(),'dense_min_action_frames_r4':(1+np.argmin(old[:-1],axis=0)/8).tolist(),'dense_min_action_frames_r5':(1+np.argmin(new[:-1],axis=0)/8).tolist(),'dense_max_action_frames_r4':(1+np.argmax(old[:-1],axis=0)/8).tolist(),'dense_max_action_frames_r5':(1+np.argmax(new[:-1],axis=0)/8).tolist(),'max_receiver_x_change_pixels':float(abs(new[:,1,0]-old[:,1,0]).max()),'tie_note':'Backward primary X equal-peak plateaus retain their trajectory; float differences below0.002px can change raw argmax among tied frames. Receiver is a coupled rigid-pose projection, not an independent control.'}
 if direction=='backward':
  oldangle=angle(old);newangle=angle(new);amin=oldangle[:-1:8].min();wanted=amin+params['screen_barrel_angle_gain']*(oldangle-amin);error=float(np.degrees(abs(newangle-wanted)).max());assert error<.01,error
  report.update({'dense_barrel_angle_constraint_max_error_degrees':error,'r4_screen_barrel_angle_range_degrees':float(np.degrees(np.ptp(oldangle[:-1:8]))),'r5_screen_barrel_angle_range_degrees':float(np.degrees(np.ptp(newangle[:-1:8]))),'barrel_angle_minmax_native_action_frames_r4':[int(np.argmin(oldangle[:-1:8]))+1,int(np.argmax(oldangle[:-1:8]))+1],'barrel_angle_minmax_native_action_frames_r5':[int(np.argmin(newangle[:-1:8]))+1,int(np.argmax(newangle[:-1:8]))+1]})
 result['actions'][names['r5']]=report
summary=json.loads((B/'validation/native_validation.json').read_text());new=[v for k,v in summary['actions'].items() if k.endswith('_r5')];assert max(max(v['max_wrist_error_m']) for v in new)<1e-6;assert max(max(v['max_guard_error_degrees']) for v in new)==0;assert all(v['loop_endpoint_root_matrix_error']==0 and v['loop_endpoint_actor_matrix_error']==0 and v['loop_endpoint_hand_matrix_error']==0 and not v['invalid_drivers'] for v in new)
result['contact_summary']={'new_action_samples_480hz':sum(v['samples_480hz'] for v in new),'max_wrist_error_m':max(max(v['max_wrist_error_m']) for v in new),'max_guard_error_degrees':0,'max_loop_endpoint_matrix_error':0,'invalid_drivers':[]};(B/'validation_summary.json').write_text(json.dumps(result,indent=2)+'\n');print(json.dumps(result,indent=2))
